import type { Client } from "@notionhq/client";
import type { PageObjectResponse } from "@notionhq/client/build/src/api-endpoints";

export type NotionItemProperty = PageObjectResponse["properties"][string];
export type NotionSelectProperty = Extract<NotionItemProperty, { type: "select" }>;
export type NotionMultipleSelectProperty = Extract<NotionItemProperty, { type: "multi_select" }>;
export type NotionRichTextProperty = Extract<NotionItemProperty, { type: "rich_text" }>;
export type NotionTitleProperty = Extract<NotionItemProperty, { type: "title" }>;
export type NotionStatusProperty = Extract<NotionItemProperty, { type: "status" }>;

export type NotionQueryDatabaseParams = Parameters<InstanceType<typeof Client>["databases"]["query"]>[0];
export type NotionQueryFilter = NonNullable<NotionQueryDatabaseParams["filter"]>;
export type NotionQueryFilterAnd = Extract<NotionQueryFilter, { and: unknown }>;
export type NotionQueryFilterOr = Extract<NotionQueryFilter, { or: unknown }>;

export type NotionCover = PageObjectResponse["cover"];
export type NotionIcon = PageObjectResponse["icon"];
export type NotionColor =
  | "default"
  | "gray"
  | "brown"
  | "orange"
  | "yellow"
  | "green"
  | "blue"
  | "purple"
  | "pink"
  | "red"
  | "gray_background"
  | "brown_background"
  | "orange_background"
  | "yellow_background"
  | "green_background"
  | "blue_background"
  | "purple_background"
  | "pink_background"
  | "red_background";

export type CodeLanguage =
  | "abap"
  | "agda"
  | "arduino"
  | "assembly"
  | "bash"
  | "basic"
  | "bnf"
  | "c"
  | "c#"
  | "c++"
  | "clojure"
  | "coffeescript"
  | "coq"
  | "css"
  | "dart"
  | "dhall"
  | "diff"
  | "docker"
  | "ebnf"
  | "elixir"
  | "elm"
  | "erlang"
  | "f#"
  | "flow"
  | "fortran"
  | "gherkin"
  | "glsl"
  | "go"
  | "graphql"
  | "groovy"
  | "haskell"
  | "html"
  | "idris"
  | "java"
  | "javascript"
  | "json"
  | "julia"
  | "kotlin"
  | "latex"
  | "less"
  | "lisp"
  | "livescript"
  | "llvm ir"
  | "lua"
  | "makefile"
  | "markdown"
  | "markup"
  | "matlab"
  | "mathematica"
  | "mermaid"
  | "nix"
  | "notion formula"
  | "objective-c"
  | "ocaml"
  | "pascal"
  | "perl"
  | "php"
  | "plain text"
  | "powershell"
  | "prolog"
  | "protobuf"
  | "purescript"
  | "python"
  | "r"
  | "racket"
  | "reason"
  | "ruby"
  | "rust"
  | "sass"
  | "scala"
  | "scheme"
  | "scss"
  | "shell"
  | "solidity"
  | "sql"
  | "swift"
  | "toml"
  | "typescript"
  | "vb.net"
  | "verilog"
  | "vhdl"
  | "visual basic"
  | "webassembly"
  | "xml"
  | "yaml"
  | "java/c/c++/c#";
